name: Link Checker

on:
  push:
    branches:
      - main

  schedule:
    - cron: "0 6 * * 1"

  workflow_dispatch:

jobs:
  link-check:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Check links
        uses: lycheeverse/lychee-action@8646ba30535128ac92d33dfc9133794bfdd9b411

        with:
          args: >
            --verbose
            --no-progress
            --accept 200,429
            --timeout 20
            --dump
            .